[phases.setup]
nixPkgs = ['php81', 'nginx', 'libmysqlclient', 'php81Packages.composer', 'nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['mkdir -p /var/log/nginx', 'mkdir -p /var/cache/nginx', 'composer install --ignore-platform-reqs']

[phases.build]
cmds = []

[start]
cmd = 'node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)'

[variables]
NIXPACKS_PHP_ROOT_DIR = '/app/public'

[static_assets]
'/app/public' = '/'

[[directives]]
# Վերահասցեագրել բոլոր հարցումները index.php-ին
test = '^/(.*)$'
rewrite = '/index.php/$1'