[build]
builder = "NIXPACKS"
nixpacksPlan = { providers = ["php"], versions = ["8.1"] }

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
multiRegionConfig = { europe-west4-drams3a = { numReplicas = 1 } }
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "php -S 0.0.0.0:$PORT -t public"
